banco/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

urlpatterns = [
    path('clientes', views.listar_clientes, name='listar_clientes'),
    path('clientes/novo/', views.criar_clientes, name='criar_clientes'),
    path('clientes/editar/<int:id>/', views.atualizar_cliente, name='atualizar_cliente'),
    path('clientes/deletar/<int:id>/', views.deletar_cliente, name='deletar_cliente'),
    path('exportar_clientes_pdf/', views.exportar_clientes_pdf, name='exportar_clientes_pdf'),

    path('cartoes', views.listar_cartoes, name='listar_cartoes'),
    path('cartoes/novo/', views.solicitar_cartao, name='solicitar_cartao'),
    path('cartoes/limite/<int:id>/', views.solicitar_limite, name='solicitar_limite'),
    path('cartoes/cancelar/<int:id>/', views.cancelar_cartao, name='cancelar_cartao'),
    path('exportar_cartoes_pdf/', views.exportar_cartao_pdf, name='exportar_cartoes_pdf'),


    path('emprestimo', views.listar_emprestimo, name='listar_emprestimo'),
    path('emprestimo/novo/', views.solicitar_emprestimo, name='solicitar_emprestimo'),
    path('emprestimo/cancelar/<int:id>/', views.cancelar_emprestimo, name='cancelar_emprestimo'),

    path('login/', auth_views.LoginView.as_view(template_name='usuario/login.html'), name='login'),
    
    # URL para fazer logout
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

sistemabancario/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('banco/', include('banco.urls')),
    path('usuario/', include('usuario.urls')),
]

banco/models.py
from django.db import models

class Cliente(models.Model):
    nome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return self.nome+ ' - ' +self.cpf
    
class Cartao(models.Model):
    empresa_responsavel = models.TextField()
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    limite = models.DecimalField(max_digits=4, decimal_places=2)

    def __str__(self): 
        return f"{self.cliente} - {self.limite}"
    
class Emprestimo(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    valorEmprestimo = models.CharField(max_length=15)
    prazo = models.DateField()

    def __str__(self): 
        return f"{self.cliente} - {self.valorEmprestimo} - {self.prazo}"

banco/forms.py
from django import forms
from .models import Cliente
from .models import Cartao
from .models import Emprestimo

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'cpf']

class CartaoForm(forms.ModelForm):
    class Meta:
        model = Cartao
        fields = ['empresa_responsavel', 'cliente', 'limite']

class EmprestimoForm(forms.ModelForm):
    class Meta:
        model = Emprestimo
        fields = ['cliente', 'valorEmprestimo', 'prazo']

banco/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cliente
from .forms import ClienteForm
from .models import Cartao
from .forms import CartaoForm
from .forms import EmprestimoForm
from .models import Emprestimo
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from weasyprint import HTML
from django.http import HttpResponse
from django.template.loader import render_to_string

Usuario = get_user_model()

# @login_required
def listar_clientes(request):
    clientes = Cliente.objects.all()
    return render(request, 'clientes/listar_clientes.html', {'clientes': clientes})

@login_required
def criar_clientes(request):
    if request.method == "POST":
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_clientes')

    else:
        form = ClienteForm()
    return render(request, 'clientes/criar_clientes.html', {'form': form})

@login_required
def atualizar_cliente(request, id):
    cliente = get_object_or_404(Cliente, id=id)
    if request.method == "POST":
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('listar_clientes')
    else:
        form = ClienteForm(instance=cliente)
    return render(request, 'clientes/atualizar_cliente.html', {'form': form})

@login_required
def deletar_cliente(request, id):
    cliente = get_object_or_404(Cliente, id=id)
    if request.method == "POST":
        cliente.delete()
        return redirect('listar_clientes')
    return render(request, 'clientes/deletar_cliente.html', {'cliente': cliente})

# @login_required
def exportar_clientes_pdf(request):
    # Buscando todos os usuários
    clientes = Cliente.objects.all()

    # Renderizando o template HTML com os dados dos usuários
    html_string = render_to_string('clientes/clientes_pdf.html', {'clientes': clientes})

    # Criando a resposta HTTP para o PDF
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; filename="clientes.pdf"'

    # Convertendo o HTML para PDF usando WeasyPrint
    HTML(string=html_string).write_pdf(response)

    return response

# @login_required
def exportar_cartao_pdf(request):
    # Buscando todos os usuários
    cartoes = Cartao.objects.all()

    # Renderizando o template HTML com os dados dos usuários
    html_string = render_to_string('cartoes/cartoes_pdf.html', {'cartoes': cartoes})

    # Criando a resposta HTTP para o PDF
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; filename="clientes.pdf"'

    # Convertendo o HTML para PDF usando WeasyPrint
    HTML(string=html_string).write_pdf(response)

    return response

# @login_required
def listar_cartoes(request):
    cartoes = Cartao.objects.all()
    return render(request, 'cartoes/listar_cartoes.html', {'cartoes': cartoes})

@login_required
def solicitar_cartao(request):
    if request.method == "POST":
        form = CartaoForm(request.POST)
        if form.is_valid():
            cartao = form.save()
            print('teste1')
            print(cartao)
            return redirect('listar_cartoes')
    else:
        form = CartaoForm()
    return render(request, 'cartoes/solicitar_cartao.html', {'form': form})

@login_required
def solicitar_limite(request, id):
    cartao = get_object_or_404(Cartao, id=id)
    if request.method == "POST":
        form = CartaoForm(request.POST, instance=cartao)
        if form.is_valid():
            form.save()
            return redirect('listar_cartoes')
    else:
        form = CartaoForm(instance=cartao)
    return render(request, 'cartoes/solicitar_limite.html', {'form': form})

@login_required
def cancelar_cartao(request, id):
    cartao = get_object_or_404(Cartao, id=id)
    if request.method == "POST":
        cartao.delete()
        # Redireciona para a lista de pedidos
        return redirect('listar_cartoes')
    return render(request, 'cartoes/cancelar_cartao.html', {'cartoes': cartao})

def listar_emprestimo(request):
    emprestimo = Emprestimo.objects.all()
    return render(request, 'emprestimo/listar_emprestimo.html', {'emprestimo': emprestimo})

@login_required
def cancelar_emprestimo(request, id):
    emprestimo = get_object_or_404(Emprestimo, id=id)
    if request.method == "POST":
        emprestimo.delete()
        # Redireciona para a lista de pedidos
        return redirect('listar_emprestimo')
    return render(request, 'emprestimo/cancelar_emprestimo.html', {'emprestimo': emprestimo})

@login_required
def solicitar_emprestimo(request):
    if request.method == "POST":
        form = EmprestimoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_emprestimo')
    else:
        form = EmprestimoForm()
    return render(request, 'emprestimo/solicitar_emprestimo.html', {'form': form})

banco/templates/emprestimo/cancelar_emprestimo.html
<h1>Deletar emprestimo</h1>
<p>Tem certeza que deseja deletar {{ pedido.descricao }}?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Deletar</button>
</form>
<a href="{% url 'listar_pedidos' %}">Voltar</a>

banco/templates/emprestimo/listar_emprestimo.html
{% extends "base.html" %}
{% load static %}
{% block 'dashboard' %}
<h1 class="my-4">Lista de Emprestimos</h1>
<a href="{% url 'solicitar_emprestimo' %}" class="btn colorprimarybtn2 mb-3">Solicitar Emprestimo</a>
<a href="{% url 'listar_clientes' %}" class="btn colorprimarybtn2 mb-3">Verificar Cliente</a>
<table class="table table-striped">
  <thead>
    <tr>
      
      <th>Cliente</th>
      <th>Valor do emprestimo</th>
      <th>Prazo</th>
    </tr>
  </thead>
  <tbody>
    {% for emprestimo in emprestimo %}
    <tr>
      <td>{{ emprestimo.cliente }}</td>
      <td>{{ emprestimo.valorEmprestimo }}</td>
      <td>{{ emprestimo.prazo }}</td>
      <td>
        <!-- Botão para deletar com confirmação -->
        <form action="{% url 'cancelar_emprestimo' emprestimo.id %}" method="POST" style="display:inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Tem certeza que deseja cancelar?');">Cancelar</button>
        </form>
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="3">Nenhum emprestimo solicitado.</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

banco/templates/emprestimo/solicitar_emprestimo.html
{% extends "base.html" %}
{% load static %}
{% block 'dashboard' %}
<h1 class="my-4">Criar emprestimo</h1>

<form method="post" class="needs-validation" novalidate>
    {% csrf_token %}
    
    <div class="row">
        <div class="form-group col-md-3">
            <label for="id_cliente">Cliente</label>
            <input type="text" class="form-control {% if form.cliente.errors %}is-invalid{% endif %}" 
                   id="id_cliente" name="cliente" value="{{ form.cliente.value|default_if_none:'' }}" maxlength="50" required>
            {% if form.cliente.errors %}
            <div class="invalid-feedback">{{ form.cliente.errors }}</div>
            {% endif %}
        </div>

        <div class="form-group col-md-3">
            <label for="id_valorEmprestimo">Valor do Empréstimo</label>
            <input type="text" class="form-control {% if form.valorEmprestimo.errors %}is-invalid{% endif %}" 
                   id="id_valorEmprestimo" name="valorEmprestimo" value="{{ form.valorEmprestimo.value|default_if_none:'' }}" maxlength="50" required>
            {% if form.valorEmprestimo.errors %}
            <div class="invalid-feedback">{{ form.valorEmprestimo.errors }}</div>
            {% endif %}
        </div>

        <div class="form-group col-md-6">
            <label for="id_prazo">Data</label>
            <input type="date" class="form-control {% if form.prazo.errors %}is-invalid{% endif %}" 
                   id="id_prazo" name="prazo" value="{{ form.prazo.value|default_if_none:'' }}" maxlength="4" required>
            {% if form.prazo.errors %}
            <div class="invalid-feedback">{{ form.prazo.errors }}</div>
            {% endif %}
        </div>

    </div>
    <br>
    <!-- Botões -->
    <button type="submit" class="btn btn-success">Salvar</button>
    <a href="{% url 'solicitar_emprestimo' %}" class="btn btn-secondary ml-2">Voltar</a>
</form>

{% endblock %}