banco/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

urlpatterns = [
    path('clientes', views.listar_clientes, name='listar_clientes'),
    path('clientes/novo/', views.criar_clientes, name='criar_clientes'),
    path('clientes/editar/<int:id>/', views.atualizar_cliente, name='atualizar_cliente'),
    path('clientes/deletar/<int:id>/', views.deletar_cliente, name='deletar_cliente'),
    path('exportar_clientes_pdf/', views.exportar_clientes_pdf, name='exportar_clientes_pdf'),

    path('cartoes', views.listar_cartoes, name='listar_cartoes'),
    path('cartoes/novo/', views.solicitar_cartao, name='solicitar_cartao'),
    path('cartoes/limite/<int:id>/', views.solicitar_limite, name='solicitar_limite'),
    path('cartoes/cancelar/<int:id>/', views.cancelar_cartao, name='cancelar_cartao'),
    path('exportar_cartoes_pdf/', views.exportar_cartao_pdf, name='exportar_cartoes_pdf'),


    path('emprestimo', views.listar_emprestimo, name='listar_emprestimo'),
    path('emprestimo/novo/', views.solicitar_emprestimo, name='solicitar_emprestimo'),
    path('emprestimo/cancelar/<int:id>/', views.cancelar_emprestimo, name='cancelar_emprestimo'),

    path('login/', auth_views.LoginView.as_view(template_name='usuario/login.html'), name='login'),
    
    # URL para fazer logout
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

sistemabancario/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('banco/', include('banco.urls')),
    path('usuario/', include('usuario.urls')),
]

banco/models.py
from django.db import models

class Cliente(models.Model):
    nome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return self.nome+ ' - ' +self.cpf
    
class Cartao(models.Model):
    empresa_responsavel = models.TextField()
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    limite = models.DecimalField(max_digits=4, decimal_places=2)

    def __str__(self): 
        return f"{self.cliente} - {self.limite}"
    
class Emprestimo(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    valorEmprestimo = models.CharField(max_length=15)
    prazo = models.DateField()

    def __str__(self): 
        return f"{self.cliente} - {self.valorEmprestimo} - {self.prazo}"

banco/forms.py
from django import forms
from .models import Cliente
from .models import Cartao
from .models import Emprestimo

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'cpf']

class CartaoForm(forms.ModelForm):
    class Meta:
        model = Cartao
        fields = ['empresa_responsavel', 'cliente', 'limite']

class EmprestimoForm(forms.ModelForm):
    class Meta:
        model = Emprestimo
        fields = ['cliente', 'valorEmprestimo', 'prazo']

banco/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cliente
from .forms import ClienteForm
from .models import Cartao
from .forms import CartaoForm
from .forms import EmprestimoForm
from .models import Emprestimo
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from weasyprint import HTML
from django.http import HttpResponse
from django.template.loader import render_to_string

Usuario = get_user_model()

# @login_required
def listar_clientes(request):
    clientes = Cliente.objects.all()
    return render(request, 'clientes/listar_clientes.html', {'clientes': clientes})

@login_required
def criar_clientes(request):
    if request.method == "POST":
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_clientes')

    else:
        form = ClienteForm()
    return render(request, 'clientes/criar_clientes.html', {'form': form})

@login_required
def atualizar_cliente(request, id):
    cliente = get_object_or_404(Cliente, id=id)
    if request.method == "POST":
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('listar_clientes')
    else:
        form = ClienteForm(instance=cliente)
    return render(request, 'clientes/atualizar_cliente.html', {'form': form})

@login_required
def deletar_cliente(request, id):
    cliente = get_object_or_404(Cliente, id=id)
    if request.method == "POST":
        cliente.delete()
        return redirect('listar_clientes')
    return render(request, 'clientes/deletar_cliente.html', {'cliente': cliente})

# @login_required
def exportar_clientes_pdf(request):
    # Buscando todos os usuários
    clientes = Cliente.objects.all()

    # Renderizando o template HTML com os dados dos usuários
    html_string = render_to_string('clientes/clientes_pdf.html', {'clientes': clientes})

    # Criando a resposta HTTP para o PDF
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; filename="clientes.pdf"'

    # Convertendo o HTML para PDF usando WeasyPrint
    HTML(string=html_string).write_pdf(response)

    return response

# @login_required
def exportar_cartao_pdf(request):
    # Buscando todos os usuários
    cartoes = Cartao.objects.all()

    # Renderizando o template HTML com os dados dos usuários
    html_string = render_to_string('cartoes/cartoes_pdf.html', {'cartoes': cartoes})

    # Criando a resposta HTTP para o PDF
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; filename="clientes.pdf"'

    # Convertendo o HTML para PDF usando WeasyPrint
    HTML(string=html_string).write_pdf(response)

    return response

# @login_required
def listar_cartoes(request):
    cartoes = Cartao.objects.all()
    return render(request, 'cartoes/listar_cartoes.html', {'cartoes': cartoes})

@login_required
def solicitar_cartao(request):
    if request.method == "POST":
        form = CartaoForm(request.POST)
        if form.is_valid():
            cartao = form.save()
            print('teste1')
            print(cartao)
            return redirect('listar_cartoes')
    else:
        form = CartaoForm()
    return render(request, 'cartoes/solicitar_cartao.html', {'form': form})

@login_required
def solicitar_limite(request, id):
    cartao = get_object_or_404(Cartao, id=id)
    if request.method == "POST":
        form = CartaoForm(request.POST, instance=cartao)
        if form.is_valid():
            form.save()
            return redirect('listar_cartoes')
    else:
        form = CartaoForm(instance=cartao)
    return render(request, 'cartoes/solicitar_limite.html', {'form': form})

@login_required
def cancelar_cartao(request, id):
    cartao = get_object_or_404(Cartao, id=id)
    if request.method == "POST":
        cartao.delete()
        # Redireciona para a lista de pedidos
        return redirect('listar_cartoes')
    return render(request, 'cartoes/cancelar_cartao.html', {'cartoes': cartao})

def listar_emprestimo(request):
    emprestimo = Emprestimo.objects.all()
    return render(request, 'emprestimo/listar_emprestimo.html', {'emprestimo': emprestimo})

@login_required
def cancelar_emprestimo(request, id):
    emprestimo = get_object_or_404(Emprestimo, id=id)
    if request.method == "POST":
        emprestimo.delete()
        # Redireciona para a lista de pedidos
        return redirect('listar_emprestimo')
    return render(request, 'emprestimo/cancelar_emprestimo.html', {'emprestimo': emprestimo})

@login_required
def solicitar_emprestimo(request):
    if request.method == "POST":
        form = EmprestimoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_emprestimo')
    else:
        form = EmprestimoForm()
    return render(request, 'emprestimo/solicitar_emprestimo.html', {'form': form})

banco/templates/cartoes/cancelar_cartao.html
<h1>Cancelar Cartão</h1>
<p>Tem certeza que deseja deletar {{ pedido.descricao }}?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Deletar</button>
</form>
<a href="{% url 'listar_cartoes' %}">Voltar</a>

banco/templates/cartoes/cartoes_pdf.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Cartões</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            /* Remove as margens padrão da página */
            padding: 0;
            /* Remove o padding padrão da página */
        }

        h1 {
            text-align: center;
            color: #1E90FF;
            margin-top: 20px;
        }

        table {
            width: 100%;
            /* Faz a tabela ocupar 100% da largura da página */
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 12px;
        }

        table,
        th,
        td {
            border: 1px solid #ddd;
        }

        th,
        td {
            padding: 8px;
            text-align: left;
            word-wrap: break-word;
            /* Quebrar palavras para evitar sobreposição */
        }

        th {
            background-color: #1E90FF;
            color: white;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        /* Ajustar a largura das colunas */
        th:nth-child(2),
        td:nth-child(2) {
            width: 40%;
        }

        .container {
            width: 100%;

        }
    </style>
</head>

<body>
    <div class="info">
        <img src="/templates/static/img/logo.jpeg">
        <div>Endereço: Rua Cavalcante, 321</div>
        <div>Teresina, Piauí</div>
        <div>Telefone: (12) 3456-7890</div>
        <div>Email: bancocavalcante@empresa.com</div>
    </div>
    <div class="container">
        <h1>Cartões Cadastrados</h1>
        <table>
            <thead>
                <tr>
                    <th>Cliente</th>
                    <th>Empresa</th>
                </tr>
            </thead>
            <tbody>
                {% for cartao in cartoes %}
                <tr>
                    <td>{{ cartao.cliente.nome }}</td>
                    <td>{{ cartao.empresa_responsavel }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>

</html>

banco/templates/cartoes/listar_cartoes.html
{% extends "base.html" %}
{% load static %}
{% block 'dashboard' %}
<h1 class="my-4">Lista de Cartões</h1>
<a href="{% url 'solicitar_cartao' %}" class="btn colorprimarybtn2 mb-3">Solicitar Cartão</a>
<a href="{% url 'exportar_cartoes_pdf' %}" target="_blank" class="btn colorprimarybtn2 mb-3">Exportar PDF</a>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Empresa</th>
      <th>Cliente</th>
      <th>Limite</th>

    </tr>
  </thead>
  <tbody>
    {% for cartao in cartoes %}
    <tr>
      <td>{{ cartao.empresa_responsavel }}</td>
      <td>{{ cartao.cliente }}</td>
      <td>{{ cartao.limite }}</td>

      <td>
        <a href="{% url 'solicitar_limite' cartao.id %}" class="btn btn-sm btn-warning">Solicitar Limite</a>
        <!-- Botão para deletar com confirmação -->
        <form action="{% url 'cancelar_cartao' cartao.id %}" method="POST" style="display:inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Tem certeza que deseja cancelar este cartão?');">Cancelar</button>
        </form>
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="3">Nenhum cartão solicitado.</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

banco/templates/cartoes/solicitar_cartao.html
{% extends "base.html" %}
{% load static %}
{% block 'dashboard' %}
<h1 class="my-4">Criar Cartão</h1>

<form method="post" class="needs-validation" novalidate>
    {% csrf_token %}
    
    <div class="row">
        <div class="form-group col-md-3">
            <label for="id_empresa_responsavel">Empresa</label>
            <input type="text" class="form-control {% if form.empresa_responsavel.errors %}is-invalid{% endif %}" 
                   id="id_empresa_responsavel" name="empresa_responsavel" value="{{ form.empresa_responsavel.value|default_if_none:'' }}" maxlength="11" required>
            {% if form.empresa_responsavel.errors %}
            <div class="invalid-feedback">{{ form.empresa_responsavel.errors }}</div>
            {% endif %}
        </div>

        <div class="form-group col-md-3">
            <label for="id_cliente">Cliente</label>
            <input type="text" class="form-control {% if form.cliente.errors %}is-invalid{% endif %}" 
                   id="id_cliente" name="cliente" value="{{ form.cliente.value|default_if_none:'' }}" maxlength="50" required>
            {% if form.cliente.errors %}
            <div class="invalid-feedback">{{ form.cliente.errors }}</div>
            {% endif %}
        </div>

       <div class="form-group col-md-6">
            <label for="id_limite">Limite</label>
            <input type="number" class="form-control {% if form.limite.errors %}is-invalid{% endif %}" 
                   id="id_limite" name="limite" value="{{ form.limite.value|default_if_none:'' }}" maxlength="4" required>
            {% if form.limite.errors %}
            <div class="invalid-feedback">{{ form.limite.errors }}</div>
            {% endif %}
        </div>

    </div>
    <br>
    <!-- Botões -->
    <button type="submit" class="btn btn-success">Salvar</button>
    <a href="{% url 'listar_cartoes' %}" class="btn btn-secondary ml-2">Voltar</a>
</form>

{% endblock %}

banco/templates/cartoes/solicitar_limite.html
<h1>Atualizar Pedido</h1>
<form method="post">
    {% csrf_token %}
    <div>
        <label for="id_cliente">Cliente:</label>
        <input type="number" id="id_cliente" name="cliente" value="{{ form.cliente.value|default_if_none:'' }}" maxlength="100"
            required>
        {% if form.cliente.errors %}
        <div class="error">{{ form.cliente.errors }}</div>
        {% endif %}
    </div>

    <div>
        <label for="id_descricao">Descrição:</label>
        <input type="text" id="id_descricao" name="descricao" value="{{ form.descricao.value|default_if_none:'' }}" maxlength="11"
            required>
        {% if form.descricao.errors %}
        <div class="error">{{ form.descricao.errors }}</div>
        {% endif %}
    </div>

    <div>
        <label for="id_valor">Valor:</label>
        <input type="text" id="id_valor" name="valor" value="{{ form.valor.value|default_if_none:'' }}" maxlength="9999"
            required>
        {% if form.valor.errors %}
        <div class="error">{{ form.valor.errors }}</div>
        {% endif %}
    </div>

    <button type="submit">Salvar</button>
</form>
<a href="{% url 'listar_pedidos' %}">Voltar</a>